# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'issu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 417)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.pushButton.clicked.connect(self.issuer)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.pushButton_3)
        self.pushButton_3.clicked.connect(self.buyer)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.lineEdit_7.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_6.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_5.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_4.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_3.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_2.clicked.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Find Book"))
        self.pushButton.setText(_translate("Form", "Fetch details"))
        self.label_2.setText(_translate("Form", "Name"))
        self.label_3.setText(_translate("Form", "Cost"))
        self.label_4.setText(_translate("Form", "Copies available"))
        self.label_5.setText(_translate("Form", "Copies Needed"))
        self.label_6.setText(_translate("Form", "Final Cost"))
        self.label_7.setText(_translate("Form", "Copies remaining"))
        self.pushButton_3.setText(_translate("Form", "Buy now"))
        self.pushButton_2.setText(_translate("Form", "Clear all"))

    def issuer(self):
        x = self.lineEdit.text()
        import fetch
        y = fetch.byfirstname(x)
        if y == -1:
            self.lineEdit_2.setText('Book Not Found')
            self.lineEdit_3.setText('Book Not Found')
            self.lineEdit_4.setText('Book Not Found')
            self.lineEdit_5.setText('Book Not Found')
            self.lineEdit_6.setText('Book Not Found')
            self.lineEdit_7.setText('Book Not Found')
        else:
            if y[2] != '0':
                self.lineEdit_2.setText(y[0])
                self.lineEdit_3.setText(y[1])
                self.lineEdit_4.setText(y[2])
            else:
                self.lineEdit_2.setText(y[0])
                self.lineEdit_3.setText(y[1])
                self.lineEdit_4.setText(y[2])
                self.lineEdit_5.setText('No more copies available')
                self.lineEdit_6.setText('No more copies available')
                self.lineEdit_7.setText('No more copies available')

    def buyer(self):

        a = self.lineEdit.text()
        x = self.lineEdit_5.text()
        import fetch
        y = fetch.byfirstname(a)[2]
        cost = fetch.byfirstname(a)[1]
        if x.isnumeric():
            if int(x) > int(y):
                self.lineEdit_6.setText('Less copies are available')
                self.lineEdit_7.setText('Less copies are available')
            else:
                ax = float(x)
                c = float(cost)
                fc = ax * c
                self.lineEdit_6.setText(str(fc))
                left = str(int(y) - int(x))
                self.lineEdit_7.setText(left + " copy(s) left")
                import random
                xr = str(random.randint(1000, 9999))
                file1 = open("receipt" + xr + ".txt", "w")
                file1.write("Welcome to Hellfire Book Depot !!!! \n")
                file1.writelines("Name of the book = " + a + "\n")
                file1.writelines("Cost of the book = " + cost + "\n")
                file1.writelines("Copies issued    = " + x + "\n")
                file1.writelines("Total cost       = " + str(fc) + "\n")
                file1.writelines("Thank you for shopping with us. Come again!!")
                file1.close()
                if int(left) > -1:
                    import update
                    update.byqty(a, cost, left)

        else:
            self.lineEdit_6.setText('Enter appropriate number of copies')
            self.lineEdit_7.setText('Enter appropriate number of copies')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
